name: validate

on:
  push:
    branches: 
      - "develop"
      - "master"
      
  pull_request:
    branches:
      - "develop"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    container: slacgismo/gridlabd:latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate data
      run: utilities/autotest
      
    - name: Save results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: autotest.err
        path: autotest.err  
